namespace:
  name: sandbox
 
service:
  port: 8111
  type: ClusterIP

image:
  repository: techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    memory: 64Mi
    CPU: 250m
  limits:
    memory: 128Mi
    CPU: 500m
    
containerPort: &containerPortSpec 3111
livenessProbe:
  path: /healthz
  check: *containerPortSpec
readinessProbe:
  path: /healthz
  check: *containerPortSpec